### ISSUE TITLE
Ordinal numbers in team embeds are incorrect

### ISSUE THREAD

**Issue by aopell** [glen3b/CyPatScoreboardBot#19]
Though the cases of "1st", "2nd", and "3rd" appear to be handled correctly, all numbers over 3 have the suffix of "th" when team margins are displayed.

The same issue applies to the displayed percentile rank of teams containing decimal points, such as "1.3th place" in the image below.

![image](https://user-images.githubusercontent.com/5026980/34447372-113ead3a-ec98-11e7-913f-ff69d7fb9d36.png)
*See "2032th place" under Margin and "1.3th percentile"*

**Comment by glen3b** [comment]
How should percentile ordinals be handled?

**Comment by aopell** [comment]
Based on what I've seen on wikipedia it seems like it follows the same rules as non decimal numbers, but you just take the decimal part.

So 43.22 would be written "43.22nd percentile"
