### ISSUE TITLE
Command to get team from given percentile or rank within division+tier

### ISSUE THREAD

**Issue by lighthouse64** [glen3b/CyPatScoreboardBot#23]
Command:
!Percentile [percentile as a double] [division] [tier]

By inputting this command you would get the team that corresponds with the given percentile, just how using:
!team [teamID] 
gives you the team based on the Id given.

**Comment by aopell** [comment]
I'd also like to integrate the ability to get the team at a specific rank into this command somehow.

Command name and syntax TBD but something like `!getteam [rank] [division] [tier]` for getting the team in like 1st place for example.

**Comment by glen3b** [comment]
Good idea. The one thing that may also be useful is a more general team filter selection syntax, so for All Service teams you can get the 1st place team within your category, for instance.

**Comment by glen3b** [comment]
Rank addressed by @aopell, percentile yet to be added.
OP's format for command parameterization looks good.
