### ISSUE TITLE
Peer scoreboard command

### ISSUE THREAD

**Issue by glen3b** [glen3b/CyPatScoreboardBot#24]
Add a command to show a scoreboard for a given team's peers. For instance, in All Service, team peering is often restricted to within a category, and it might be useful to easily view a team's competitors. Could also highlight the passed team or make other adjustments applicable only to them.

Invocation could be as `peerboard`, `peerscoreboard`, `peerleaderboard, etc.
Arguments: Required team ID, optional page number

**Comment by aopell** [comment]
I would recommend that you display the 5 teams above and below the specified team and then the top 10 as well
