### ISSUE TITLE
Peer teams percentile

### ISSUE THREAD

**Issue by aopell** [glen3b/CyPatScoreboardBot#29]
As of right now, the percentile is by division. This makes sense for Round 2 => Round 3 advancement, however after Round 3 this means nothing. Team embeds should include both the division percentile and the peer team percentile.

**Comment by glen3b** [comment]
Percentile should be for peers (in R2 peers are division), can you confirm this? If not it's a bug - all unlabeled stats are for peers.

**Comment by glen3b** [comment]
The relevant line is [164 of `ScoreboardMessageBuilderService`](https://github.com/glen3b/CyPatScoreboardBot/blob/master/Services/ScoreboardMessageBuilderService.cs#L164): `double rawPercentile = 1.0 - (((double)peerTeams.Count(peer => peer.TotalScore >= teamScore.Summary.TotalScore)) / peerTeams.Count);`

This uses the peer teams list computed earlier via the competition logic service, and the currently observed behavior is consistent with what I expect to happen (both from a design and code standpoint) - percentile is computed based on peer teams. If you're observing different behavior, please tag this as a bug.

**Comment by glen3b** [comment]
Misunderstanding, already behaves as expected.
