### ISSUE TITLE
Output the statistics for each state, division, and tier

### ISSUE THREAD

**Issue by lighthouse64** [glen3b/CyPatScoreboardBot#40]
This feature would allow you to get statistics on the distributions from each state, division, and tier.
The statistics would be:
mean, median, standard deviation, lowest score, highest score

Syntax:
!statistics [state]
or
!statistics [division] [tier]

**Comment by glen3b** [comment]
Perhaps this could even be wrapped into histogram generation, and just tack on some more statistics there. The other addition, in that, case would be adding histogram overloads for location filtration.

**Comment by aopell** [comment]
Reopening, state not addressed,

**Comment by glen3b** [comment]
The stats are currently being displayed as part of the histogram command. I like doing it this way.

Histogram command is currently implemented as the following three overloads:
!histogram [image]
!histogram <division> [image]
!histogram <division> <tier> [image]

Image can be an arbitrary string, but so can location. We can implement a location type reader for string which enforces the two-letter or three-letter capital syntax, thereby limiting the overload parsing, but I worry about behavior when dealing with overloads with two optional string components.

**Comment by glen3b** [comment]
Possible syntax, with validation for location parsing using a custom overridden type reader:
```
!histogram [location = null] [image = null]
!histogram [location = null] <division> [image = null]
!histogram [location = null] <division> <tier> [image = null]
```
Potentially problematic cases:
- `!histogram Ubuntu14` - global histogram for the "Ubuntu14" image
- `!histogram MS` - I'm not sure what this should do, probably a global histogram for Mississippi, but it might be interpreted as a middle-school histogram across all locations

**Comment by glen3b** [comment]
Location support implemented roughly as described, **BUT** we've lost theoretical support for per-image scores in the process.

I'm of the opinion we shouldn't bother with per-image histograms because:
- Requires one network call per team, instead of one overall network call to get the scoreboard
- Overloading for images is very difficult (I tried)

The O(n) score access is the big thing. I'm considering the stats portion of the histogram complete.
