### ISSUE TITLE
Proper Cache Invalidation

### ISSUE THREAD

**Issue by glen3b** [glen3b/CyPatScoreboardBot#50]
Currently the various caches can be in inconsistent states. We should aim to minimize this so that we don't get odd behavior like negative points behind the next team (scoreboard older than team info or vice versa, so ranking and score comparison [w/ team detail score] inconsistent).

**Comment by lighthouse64** [comment]
Isn't this more of a bug that's being fixed rather than a feature being added?

**Comment by glen3b** [comment]
The end result is a bugfix, but internally it'd probably have to be implemented as a new interface feature - even then I don't know how exactly I want to do it. I guess the caching provider will have to check validity of returned team details, but that involves an extra call and only suppresses the more obvious cases of the issue - it doesn't solve other inconsistencies.

Complicating this issue is the fact that CCS itself has this issue: team pages can be more up-to-date than the scoreboard. I'm not sure if this problem has to do with my internal cache or with upstream CCS caching problems.

**Comment by glen3b** [comment]
Our cache intervals are short enough that, while this is a legitimate cache invalidation issue, it is *CCSs* cache invalidation problem, not our own. Closing because the inconsistent state comes straight from CCS.
