### ISSUE TITLE
Get score graphs after official scores for a round are released

### ISSUE THREAD

**Issue by lighthouse64** [glen3b/CyPatScoreboardBot#60]
Currently, CyberScores will stop showing the score graph for each team after Cyberpatriot releases the official scores for each team.  It is understandable that this is done to prevent any possible confusion if changes are made to the images.  However, it would still be nice to have access to them, in case you want to view them again.  

This feature would allow you to get the link to a score graph of a team after Cyberpatriot releases official scores by running 
`!ccsgraph <teamid>`

**Comment by glen3b** [comment]
Might just end up being implemented as running `!team` through #82, thus not necessitating even a bit of extra work.

**Comment by glen3b** [comment]
The data source prefixing I think should be more than enough to avoid confusion, not to mention that data sourcing info would be plastered all over the returned information. It also saves additional implementation work.

**Comment by glen3b** [comment]
Possible with properly-configured (on bot owner's end) alternate data sources via the new command introduced in #82. Closing as fixed.
