### ISSUE TITLE
Show score time on team embeds

### ISSUE THREAD

**Issue by glen3b** [glen3b/CyPatScoreboardBot#67]
Score time is not clearly displayed on team embeds. We should consider showing it.

**Comment by glen3b** [comment]
Perhaps a line on the graph for when score time was achieved would be doable.

**Comment by aopell** [comment]
See the `V` property of the `chm` attribute for Google static charts: https://developers.google.com/chart/image/docs/gallery/line_charts#shape-markers-chm-bar-line----radar-scatter
