### ISSUE TITLE
It is impossible to sort scores by cisco performance

### ISSUE THREAD

**Issue by lighthouse64** [glen3b/CyPatScoreboardBot#86]
Currently, the name for the cisco score category is ``Cisco (Total)``, so it is impossible to use the imagescoreboard command with it because there is a space.

**Comment by glen3b** [comment]
Use quotes. String parameters, like image name, support spaces if properly quoted. If using spaces doesn't resolve the issue it can be reopened.

`!histogram "Cisco (Total)"` should work.
