### ISSUE TITLE
Should be easy af but like easy thingys for dem noobs

### ISSUE THREAD

**Issue by james8bc** [glen3b/CyPatScoreboardBot#92]
So like we are lazy nerd n00bZ and why would we type the long ass thing for ccsarchiveround3cyberpatriotthisisalongthing and all ubuntu16anupdatefromubuntu15thatisolderthanubuntu17onlyformiddleschoolnoobies

so it should be like !archive r3 windows10plat

yeah u get it, rite?

**Comment by aboatcallie** [comment]
https://gyazo.com/6dd6f295b8b2de097280478e7431b1e6
Dev response loool

**Comment by glen3b** [comment]
I'm unclear what you mean here. Could you edit this issue to make more sense or open a new, more coherent issue? Until then, this issue is invalid.

**Comment by james8bc** [comment]
you did it lol
