### ISSUE TITLE
Scoreboard format changes in CPXII semifinals

### ISSUE THREAD

**Issue by glen3b** [glen3b/CyPatScoreboardBot#94]
According to the author, there are impending changes to the scoreboard format for semifinals. @aopell I've detailed them to you privately (I'm not sure if I should publicize them), so if you could help tweak the bot to handle them (shouldn't be too hard but takes time), that would be great.

**Comment by aopell** [comment]
I believe this to be addressed and fixed in a7111f733137a3e306599c1f2569614a4ba03aa9
