### ISSUE TITLE
Bot not linked to new scoreboard

### ISSUE THREAD

**Issue by arjunghoshal** [glen3b/CyPatScoreboardBot#97]
The new scoreboard is up for the new season, and round 1 is currently live, but the bot does not use this scoreboard, it is still using last season's semifinals scoreboard.

**Comment by matthewzring** [comment]
The developer is aware of this and working on updating the bot. It should be completed sometime today.

**Comment by arjunghoshal** [comment]
Perfect thanks!

**Comment by glen3b** [comment]
Fixed in production.
