### ISSUE TITLE
How to Use bot?

### ISSUE THREAD

**Issue by MrKomodoDragon** [glen3b/CyPatScoreboardBot#98]
Hi all,

I added the bot to my server, however i dont know how to use it. can someone show me?

**Comment by glen3b** [comment]
The bot doesn't have a prefix set by default - it responds to pings. You probably want to do `@CyberScores admin prefix set <your prefix character>`, and then you can run help to see the list of commands.

**Comment by MrKomodoDragon** [comment]
Ok thanks
!
